# Generated by Django 4.1.5 on 2023-11-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=60)),
                ('telefono_cliente', models.CharField(max_length=12)),
                ('correo_cliente', models.CharField(max_length=70)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellido_empleado', models.CharField(max_length=50)),
                ('direccion_empleado', models.CharField(max_length=60)),
                ('telefono_empleado', models.CharField(max_length=12)),
                ('correo_empleado', models.CharField(max_length=70)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facturacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_informe', models.CharField(max_length=20)),
                ('fecha_informe', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=70)),
                ('telefono_proveedor', models.CharField(max_length=12)),
                ('correo_proveedor', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('precio_servicio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('Facturacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.facturacion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.orden_pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.rubro_proveedor'),
        ),
        migrations.AddField(
            model_name='orden_pedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviexpress.proveedor'),
        ),
    ]
